name: Request New Domain or Variable
description: Request New Domain or Variable.
title: "Request New Domain or Variable: <Insert Issue Title Here>"
labels: ["Request New Domain or Variable"]
assignees:
  - octocat
body:
  - type: textarea
    id: domain
    attributes:
      label: Domain/Variable Addition
      description: Please provide the requested domain name, variable name, and associated variable metadata (type).
      placeholder: "Example:  **Details:**
      1. **Domain Name:** AE (Adverse Events)
      1b. **Domain dependencies (optional):**
      2. **Variable Name(s):** AESEV
      2b. **Source Column Name(s) (optional):**
      3. **Variable Metadata:**: **Data Type:** Character"
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Rationale for Addition:
      description: Please provide a reason for the addition, such as the deliverable or the desired outcome.
      placeholder: "Example:
   - This variable is required to assess the severity of adverse events in real-time and identify critical safety issues.
   - Severity classification is essential for regulatory reporting and decision-making."
    validations:
      required: false
